### ISSUE TITLE
Can anyone help me with this error?

### ISSUE THREAD

**Issue by ghost** [mikeanthonywild/gpu-driver-swap#8]
When running the command: systemctl status gpu-driver-swap.service

gpu-driver-swap.service - Service to automatically swap AMD/Nvidia drivers on boot
   Loaded: loaded (/etc/systemd/system/gpu-driver-swap.service; enabled)
   Active: failed (Result: exit-code) since Seg 2015-09-21 01:04:33 BRT; 16min ago
  Process: 3173 ExecStart=/bin/sh /usr/lib/systemd/scripts/gpuswap.sh (code=exited, status=1/FAILURE)
 Main PID: 3173 (code=exited, status=1/FAILURE)

Set 21 01:04:33 RegataOS-desktop.regataos sh[3173]: 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/... 230 OEM]
Set 21 01:04:33 RegataOS-desktop.regataos sh[3173]: Using fglrx driver
Set 21 01:04:33 RegataOS-desktop.regataos sh[3173]: Linking libglx.so...OK
Set 21 01:04:33 RegataOS-desktop.regataos sh[3173]: Linking libGL.so.1...OK
Set 21 01:04:33 RegataOS-desktop.regataos sh[3173]: Linking xorg.conf...ERROR
Set 21 01:04:33 RegataOS-desktop.regataos sh[3173]: Couldn't find /SW-SCRT-0030/bladeConfig/xorg.conf.S4000X
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by mikeanthonywild** [comment]
You're getting this error because you haven't specified where your AMD Xorg config file is. You want to create a copy of your current Xorg config (I'm assuming it's the one currently in use):

```
cp /etc/X11/xorg.conf /etc/X11/xorg.conf.amd
```

And then edit line 23 in _/usr/lib/systemd/scripts/gpuswap.sh_:

```
xorg_path=/etc/X11/xorg.conf.amd
```

Let me know if you have any issues.

**Comment by ghost** [comment]
I'm adapting to openSUSE. I will do some experiments. Your suggestion worked, thank you! I will comment on what occurs. Thanks for support Intel! :)

**Comment by ghost** [comment]
Which Linux distribution you use to run the tests?

**Comment by mikeanthonywild** [comment]
This was tested under openSUSE 13.2.

**Comment by ghost** [comment]
Then, you could help me and tell what directory you used in your tests for the Intel driver file "libGL.so.intel"? I'm also using openSUSE.

**Comment by mikeanthonywild** [comment]
Intel installs _libGL.so_ into _/usr/lib64_, however this file is overwritten when you install a proprietary driver (Nvidia or AMD). To get _libGL.so.intel_ I simply copied the original Intel file at _/usr/lib64/libGL.so_. 

To get this file back so you can rename it (as required by the script), you will either need to reinstall your system and copy the file before installing Nvidia / AMD drivers. You might be able to get it by installing `mesa`, `mesa-libgl1` and `xf86-video-intel`.

**Comment by ghost** [comment]
Hello, thank you! It has worked well for me with GPU Intel / AMD in openSUSE. However, I have not NVIDIA hardware and this prevents me from having the file "xorg.conf.nvidia". You could say the contents of your file "xorg.conf.nvidia"? (Google Translate)

**Comment by mikeanthonywild** [comment]
This is not a problem :) So, you need two sets of files:

## Intel
- _xorg.conf.intel_
- _libGL.so.intel_
- _libglx.so.intel_

## AMD
- _xorg.conf.amd_
- _libGL.so.amd_
- _libglx.so.amd_

You do **not** need Nvidia files - you can forget about these!

When you turn your PC on, it will detect the card (Intel or AMD) and will load the correct files.

**Comment by ghost** [comment]
Yes, and it has worked very well for me. :)
However, I would like to create an installer for anyone to use, regardless of the setting and also implement in my project, the Linux distribution Regata OS. So anyone could use without setting anything because the installer comes with preconfigured files, such as Intel (libGL.so.intel and libglx.so.intel (depending on whether openSUSE or Ubuntu, for example)) and including the files "xorg.conf.amd" and "xorg.conf.nvidia" (in the case of openSUSE, apparently the file "xorg.conf.intel" is not necessary, at least for me, just appended set up like this: "xorg_path=/etc/X11/". But if you have the file "xorg. conf.intel "it would be interesting to see the content.).

I enconrei some examples of xorg.conf.nvidia files on forums, but do not know whether it will work, so if you have, could you help me? Thank you! Its design is very good. When the installer for openSUSE are ready I send the link to you. :)

I will give due credit when I create the installer to the openSUSE.  ;)

 (Google Translate)

**Comment by mikeanthonywild** [comment]
Ah I'm sorry I didn't understand you before - I am glad the Intel code is working for you.

The nice thing is that the only **essential** item to put in your _xorg.conf_ is the driver like so:

```
# Nvidia example
Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
EndSection

# AMD example
Section "Device"
    Identifier    "aticonfig-Device[0]-0"
    Driver        "fglrx"
EndSection

# Intel example
Section "Device"
    Identifier    "Intel Graphics"
    Driver        "intel"
EndSection
```

Everything else should hopefully auto-configure itself.

Hope this helps.

**Comment by ghost** [comment]
Yes, thank you!
I believe it will work fine now for everyone. :ice_cream:  :D

A question occurred to me: You can install two NVIDIA drivers on the same system for GPUs, recent and old (eg driver 'NVIDIA 340.93' and 'NVIDIA 352.41'), and the system will automatically decetar configuration and GPU installed?

(Google Translate)

**Comment by mikeanthonywild** [comment]
No problem :)

This would be slightly more tricky because every time you update your
Nvidia driver (using the installer at least), it overwrites all of the old
files. I think this would be harder than just swapping the libGL and
xorg.conf files around - you would need to manually load a lot of others
too (I am not sure which ones though!).

**Comment by ghost** [comment]
OK, thank you! :)

In the case of an old GPU (GeForce 300 Series and older), the script could point to an open-source driver, eg xf86-video-nv or xf86-video-nouveau. Anyway, I leave as a suggestion. :)
